image:
  file: .gitpod.Dockerfile

ports:
  - port: 4000
    onOpen: open-browser

tasks:
  - init: 'mix deps.get && npm install --prefix ./assets/ && source gitpod_env.sh'
  - command: 'mix deps.get && source gitpod_env.sh && mix phx.server'
    openMode: split-right

vscode:
  extensions:
    - elixir-lsp.elixir-ls@0.6.2:j/OgOgkgo0QJRBdZXhmoUQ==