image:
  file: .gitpod.Dockerfile

ports:
  - port: 4000
    onOpen: open-browser

tasks:
  - init: 'mix deps.get; cd assets && npm install'
    command: 'source gitpod_env.sh; mix phx.server'

vscode:
  extensions:
    - elixir-lsp.elixir-ls@0.6.2:j/OgOgkgo0QJRBdZXhmoUQ==